
# Streamlit configuration file

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[theme]
primaryColor = "#3CB371"  # Medium Sea Green
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F8FF"  # AliceBlue
textColor = "#262730"
font = "sans serif"

[logger]
level = "info"
